# Generated by Django 5.1.3 on 2024-11-07 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateField(default=django.utils.timezone.now)),
                ('pages', models.IntegerField()),
                ('language', models.CharField(default='English', max_length=50)),
            ],
        ),
    ]
