# Generated by Django 5.1.3 on 2024-11-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publication_date']},
        ),
    ]
