# Generated by Django 5.1.3 on 2024-11-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='front_page',
            field=models.ImageField(blank=True, default='book_front_pages/default.jpeg', null=True, upload_to='book_front_pages/'),
        ),
    ]
