# Generated by Django 5.1.3 on 2024-11-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_book_options_section_chapter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-id"]},
        ),
    ]
